import { RouteRecordRaw } from 'vue-router'

/**
 * 建议：路由 path 路径与文件夹名称相同，找文件可浏览器地址找，方便定位文件位置
 *
 * 路由meta对象参数说明
 * meta: {
 *      title:          菜单栏及 tagsView 栏、菜单搜索名称（国际化）
 *      isLink：        是否超链接菜单，开启外链条件，`1、isLink: 链接地址不为空 2、isIframe:false`
 *      isHide：        是否隐藏此路由
 *      isKeepAlive：   是否缓存组件状态
 *      isAffix：       是否固定在 tagsView 栏上
 *      isIframe：      是否内嵌窗口，开启条件，`1、isIframe:true 2、isLink：链接地址不为空`
 *      roles：         当前路由权限标识，取角色管理。控制路由显示、隐藏。超级管理员：admin 普通角色：common
 *      icon：          菜单、tagsView 图标，阿里：加 `iconfont xxx`，fontawesome：加 `fa xxx`
 * }
 */

// 扩展 RouteMeta 接口
declare module 'vue-router' {
  interface RouteMeta {
    title?: string
    isLink?: string
    isHide?: boolean
    isKeepAlive?: boolean
    isAffix?: boolean
    isIframe?: boolean
    roles?: string[]
    icon?: string
  }
}

/**
 * 定义动态路由
 * 前端添加路由，请在顶级节点的 `children 数组` 里添加
 * /srcdescription 未开启 isRequestRoutes 为 true 时使用（前端控制路由），开启时第一个顶级 children 的路由将被替换成接口请求回来的路由数据
 * /srcdescription 各字段请查看 `@/views/system/menu/component/addMenu.vue 下的 ruleForm`
 * /srcreturns 返回路由菜单数据
 */
export const dynamicRoutes: Array<RouteRecordRaw> = [
  {
    path: '/',
    name: '/',
    component: () => import('@/layout/index.vue'),
    redirect: '/home',
    meta: {
      isKeepAlive: true,
    },
    children: [
      {
        path: '/home',
        name: 'home',
        component: () => import('@/views/home/index.vue'),
        meta: {
          title: '首页',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: true,
          isIframe: false,
          roles: ['admin', 'director', 'finance', 'cashier', 'warehouse', 'driver', 'vouching'],
          icon: 'iconfont icon-zhuye',
        },
      },
      // {
      //   path: '/shop',
      //   name: 'shop',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/shop/index',
      //   meta: {
      //     page: 'layout/routerView/parent',
      //     title: '店铺',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin', 'director'],
      //     icon: 'ele-Magnet',
      //   },
      //   children: [
      //     {
      //       path: '/shop/index',
      //       name: 'shopIndex',
      //       component: () => import('@/views/shop/index.vue'),
      //       meta: {
      //         page: 'product/index',
      //         title: '店铺列表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director'],
      //         icon: 'ele-Magnet',
      //       },
      //     },
      //     {
      //       path: '/shop/add',
      //       name: 'shopAdd',
      //       component: () => import('@/views/shop/add.vue'),
      //       meta: {
      //         page: '/shop/add',
      //         title: '添加店铺',
      //         isLink: '',
      //         isHide: true,
      //         isKeepAlive: false,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director'],
      //         icon: '',
      //       },
      //     },
      //     {
      //       path: '/shop/edit',
      //       name: 'shopEdit',
      //       component: () => import('@/views/shop/edit.vue'),
      //       meta: {
      //         page: 'product/edit',
      //         title: '修改店铺',
      //         isLink: '',
      //         isHide: true,
      //         isKeepAlive: false,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director'],
      //         icon: '',
      //       },
      //     },
      //     {
      //       path: '/shop/product',
      //       name: 'shopProductIndex',
      //       component: () => import('@/views/shop/product/index.vue'),
      //       meta: {
      //         page: 'shop/product/index',
      //         title: '店铺商品列表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance', 'cashier'],
      //         icon: 'ele-Goods',
      //       },
      //     },
      //   ],
      // },
      {
        path: '/order',
        name: 'order',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/order/index',
        meta: {
          title: '订单',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin', 'director', 'finance', 'cashier', 'driver', 'vouching'],
          icon: 'svg-order',
        },
        children: [
          {
            path: '/order/index',
            name: 'orderIndex',
            component: () => import('@/views/order/index.vue'),
            meta: {
              page: 'order/index',
              title: '订单列表',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier', 'driver', 'vouching'],
              icon: 'svg-order',
            },
          },
          // {
          //   path: '/order/delivery',
          //   name: 'orderDeliveryIndex',
          //   component: () => import('@/views/order/delivery/index.vue'),
          //   meta: {
          //     page: 'order/delivery/index',
          //     title: '配送单列表',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director', 'finance', 'cashier'],
          //     icon: 'svg-order',
          //   },
          // },
          // {
          //   path: '/order/delivery/stat',
          //   name: 'orderDeliveryStat',
          //   component: () => import('@/views/order/delivery/stat.vue'),
          //   meta: {
          //     page: 'order/delivery/stat',
          //     title: '配送商品统计',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director', 'finance', 'cashier'],
          //     icon: 'svg-order',
          //   },
          // },
          {
            path: '/order/detail',
            name: 'orderDetail',
            component: () => import('@/views/order/detail/index.vue'),
            meta: {
              page: 'order/detail/index',
              title: '订单详情',
              isLink: '',
              isHide: true,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier', 'driver', 'vouching'],
              icon: '',
            },
          },
          {
            path: '/afterSales/index',
            name: 'afterSalesIndex',
            component: () => import('@/views/afterSales/index.vue'),
            meta: {
              page: 'afterSales/index',
              title: '售后管理',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier'],
              icon: 'svg-afterSales',
            },
          },
          {
            path: '/afterSales/detail',
            name: 'afterSalesDetail',
            component: () => import('@/views/afterSales/detail/index.vue'),
            meta: {
              page: 'afterSales/detail/index',
              title: '售后详情',
              isLink: '',
              isHide: true,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier'],
              icon: '',
            },
          },
        ],
      },
      {
        path: '/base',
        name: 'base',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/base/table',
        meta: {
          title: '基础',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin', 'director'],
          icon: 'ele-Brush',
        },
        children: [
          // {
          //   path: '/base/tab',
          //   name: 'tabList',
          //   component: () => import('@/views/base/tab/index.vue'),
          //   meta: {
          //     title: 'Tab管理',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director'],
          //     icon: 'ele-Menu',
          //   },
          // },
          // {
          //   path: '/base/classifys',
          //   name: 'classifysList',
          //   component: () => import('@/views/base/classifys/index.vue'),
          //   meta: {
          //     title: '归集管理',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director'],
          //     icon: 'ele-Orange',
          //   },
          // },
          {
            path: '/base/table',
            name: 'tableIndex',
            component: () => import('@/views/base/table/index.vue'),
            meta: {
              page: 'base/table/index',
              title: '桌位管理',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'svg-table',
            },
          },
          {
            path: '/base/game',
            name: 'gameIndex',
            component: () => import('@/views/base/game/index.vue'),
            meta: {
              page: 'base/game/index',
              title: '游戏管理',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Trophy',
            },
          },
          {
            path: '/base/beautyBadge',
            name: 'beautyBadgeIndex',
            component: () => import('@/views/base/beautyBadge/index.vue'),
            meta: {
              page: 'base/beautyBadge/index',
              title: '徽章管理',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Medal',
            },
          },
          {
            path: '/base/tableMerge',
            name: 'tableMergeIndex',
            component: () => import('@/views/base/tableMerge/index.vue'),
            meta: {
              page: 'base/tableMerge/index',
              title: '拼桌记录',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Connection',
            },
          },
          // {
          //   path: '/base/printer',
          //   name: 'printerIndex',
          //   component: () => import('@/views/base/printer/index.vue'),
          //   meta: {
          //     page: 'base/printer/index',
          //     title: '打印机管理',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director'],
          //     icon: 'svg-printer',
          //   },
          // },
          // {
          //   path: '/base/workDaySetting',
          //   name: 'workDaySetting',
          //   component: () => import('@/views/base/workDaySetting/index.vue'),
          //   meta: {
          //     page: 'base/workDaySetting/index',
          //     title: '考勤天数管理',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director'],
          //     icon: 'ele-Timer',
          //   },
          // },
        ],
      },
      // {
      //   path: '/activity',
      //   name: 'activity',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/activity/index',
      //   meta: {
      //     title: '专区',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin', 'director', 'cashier'],
      //     icon: 'ele-Brush',
      //   },
      //   children: [
      //     {
      //       path: '/activity/index',
      //       name: 'activityList',
      //       component: () => import('@/views/activity/index.vue'),
      //       meta: {
      //         title: '专区列表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-Orange',
      //       },
      //     },
      //     {
      //       path: '/activity/category',
      //       name: 'activityCategory',
      //       component: () => import('@/views/activity/category/index.vue'),
      //       meta: {
      //         title: '专区分类',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-Menu',
      //       },
      //     },
      //   ],
      // },
      {
        path: '/freebie',
        name: 'freebie',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/freebie/config',
        meta: {
          title: '免费礼品',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin', 'director', 'cashier'],
          icon: 'ele-Present',
        },
        children: [
          {
            path: '/freebie/config',
            name: 'freebieConfig',
            component: () => import('@/views/freebie/config/index.vue'),
            meta: {
              title: '礼品配置',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Setting',
            },
          },
          {
            path: '/freebie/records',
            name: 'freebieRecords',
            component: () => import('@/views/freebie/records/index.vue'),
            meta: {
              title: '领取记录',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'cashier'],
              icon: 'ele-Tickets',
            },
          },
          {
            path: '/freebie/risk',
            name: 'freebieRisk',
            component: () => import('@/views/freebie/risk/index.vue'),
            meta: {
              title: '风控封禁',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Warning',
            },
          },
        ],
      },
      {
        path: '/captain',
        name: 'captain',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/captain/audit',
        meta: {
          title: '团长分利',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin', 'director'],
          icon: 'ele-UserFilled',
        },
        children: [
          {
            path: '/captain/audit',
            name: 'captainAudit',
            component: () => import('@/views/captain/audit/index.vue'),
            meta: {
              title: '申请审核',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-DocumentChecked',
            },
          },
          {
            path: '/captain/manage',
            name: 'captainManage',
            component: () => import('@/views/captain/manage/index.vue'),
            meta: {
              title: '团长管理',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-User',
            },
          },
          {
            path: '/captain/members',
            name: 'captainMembers',
            component: () => import('@/views/captain/members/index.vue'),
            meta: {
              title: '团员关系',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Connection',
            },
          },
        ],
      },
      {
        path: '/product',
        name: 'product',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/product/index',
        meta: {
          title: '商品',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin', 'director', 'cashier'],
          icon: 'ele-Goods',
        },
        children: [
          {
            path: '/product/index',
            name: 'productIndex',
            component: () => import('@/views/product/index.vue'),
            meta: {
              page: 'product/index',
              title: '商品列表',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'cashier'],
              icon: 'ele-Goods',
            },
          },
          {
            path: '/product/setDetail',
            name: 'setDetail',
            component: () => import('@/views/product/set/detail/index.vue'),
            meta: {
              page: 'product/set/index',
              title: '商品套餐详情',
              isLink: '',
              isHide: true,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'cashier'],
              icon: 'ele-Goods',
            },
          },
          // {
          //   path: '/product/attr',
          //   name: 'productAttr',
          //   component: () => import('@/views/product/attr/index.vue'),
          //   meta: {
          //     page: 'product/attr/index',
          //     title: '商品规格',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director', 'cashier'],
          //     icon: 'ele-Magnet',
          //   },
          // },
          // {
          //   path: '/product/mail',
          //   name: 'productMail',
          //   component: () => import('@/views/product/mail/index.vue'),
          //   meta: {
          //     title: '运费管理',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director'],
          //     icon: 'ele-Box',
          //   },
          // },
          {
            path: '/product/add',
            name: 'productAdd',
            component: () => import('@/views/product/add.vue'),
            meta: {
              title: '添加商品',
              isLink: '',
              isHide: true,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: '',
            },
          },
          {
            path: '/product/category',
            name: 'productCategory',
            component: () => import('@/views/product/category/index.vue'),
            meta: {
              title: '商品分类',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'ele-Menu',
            },
          },
          {
            path: '/product/edit',
            name: 'productEdit',
            component: () => import('@/views/product/edit.vue'),
            meta: {
              title: '修改商品',
              isLink: '',
              isHide: true,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: '',
            },
          },
          {
            path: '/product/item',
            name: 'productItem',
            component: () => import('@/views/product/item/index.vue'),
            meta: {
              title: '平台类目',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'ele-Menu',
            },
          },
        ],
      },
      // {
      //   path: '/stock',
      //   name: 'stock',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/stock/index',
      //   meta: {
      //     title: '库存',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin', 'director', 'warehouse'],
      //     icon: 'ele-Goods',
      //   },
      //   children: [
      //     {
      //       path: '/stock/index',
      //       name: 'stockIndex',
      //       component: () => import('@/views/stock/index.vue'),
      //       meta: {
      //         page: 'stock/index',
      //         title: '库存记录',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'warehouse'],
      //         icon: 'ele-Goods',
      //       },
      //     },
      //     {
      //       path: '/stock/log',
      //       name: 'stockLog',
      //       component: () => import('@/views/stock/log/index.vue'),
      //       meta: {
      //         page: 'stock/log/index',
      //         title: '库存日志',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'warehouse'],
      //         icon: 'ele-Magnet',
      //       },
      //     },
      //   ],
      // },
      {
        path: '/member',
        name: 'member',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/member/index',
        meta: {
          title: '用户',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin'],
          icon: 'ele-User',
        },
        children: [
          {
            path: '/member/index',
            name: 'memberIndex',
            component: () => import('@/views/member/index.vue'),
            meta: {
              title: '用户列表',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier'],
              icon: 'ele-User',
            },
          },
          {
            path: '/member/interestTag',
            name: 'interestTagIndex',
            component: () => import('@/views/member/interestTag/index.vue'),
            meta: {
              title: '兴趣标签',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'ele-PriceTag',
            },
          },
          {
            path: '/member/detail',
            name: 'memberDetail',
            component: () => import('@/views/member/detail/index.vue'),
            meta: {
              title: '用户详情',
              isLink: '',
              isHide: true,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier'],
              icon: 'ele-User',
            },
          },
          // {
          //   path: '/member/coupon/list',
          //   name: 'memberCouponList',
          //   component: () =>
          //     import('@/views/market/coupons/record/index.vue'),
          //   meta: {
          //     title: '用户优惠券列表',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director', 'cashier'],
          //     icon: 'ele-User',
          //   },
          // },
          // {
          //   path: '/member/card/record',
          //   name: 'memberCardList',
          //   component: () =>
          //     import('@/views/market/card/record/index.vue'),
          //   meta: {
          //     title: '用户卡券列表',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director', 'cashier'],
          //     icon: 'ele-User',
          //   },
          // },
          {
            path: '/member/shopAdmin',
            name: 'memberShopAdmin',
            component: () => import('@/views/member/shopAdmin/index.vue'),
            meta: {
              title: '管理人员',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'ele-UserFilled',
            },
          },
          {
            path: '/member/inviteRecord',
            name: 'memberInviteRecord',
            component: () => import('@/views/member/inviteRecord/index.vue'),
            meta: {
              title: '邀约记录',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'cashier'],
              icon: 'ele-Share',
            },
          },
          {
            path: '/member/car',
            name: 'memberCar',
            component: () => import('@/views/member/car/index.vue'),
            meta: {
              title: '车辆认证',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director'],
              icon: 'ele-Van',
            },
          },
          // {
          //   path: '/member/grade/index',
          //   name: 'memberShop',
          //   component: () => import('@/views/member/grade/index.vue'),
          //   meta: {
          //     title: '用户等级',
          //     isLink: '',
          //     isHide: false,
          //     isKeepAlive: true,
          //     isAffix: false,
          //     isIframe: false,
          //     roles: ['admin', 'director'],
          //     icon: 'ele-User',
          //   },
          // },
        ],
      },
      // {
      //   path: '/market',
      //   name: 'market',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/market/carousels',
      //   meta: {
      //     title: '营销',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin', 'director', 'cashier'],
      //     icon: 'ele-MagicStick',
      //   },
      //   children: [
      //     {
      //       path: '/market/combination',
      //       name: 'combination',
      //       meta: {
      //         title: '拼团管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-Stopwatch',
      //       },
      //       children: [
      //         {
      //           path: '/market/combinationStore',
      //           name: 'combinationStore',
      //           component: () => import('@/views/market/combination/index.vue'),
      //           meta: {
      //             title: '拼团商品',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-ScaleToOriginal',
      //           },
      //         },
      //         {
      //           path: '/market/combinationList',
      //           name: 'combinationnList',
      //           component: () => import('@/views/market/combination/combinaList.vue'),
      //           meta: {
      //             title: '拼团列表',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-ScaleToOriginal',
      //           },
      //         },
      //         {
      //           path: '/combination/add',
      //           name: 'combinationAdd',
      //           component: () => import('@/views/market/combination/add.vue'),
      //           meta: {
      //             title: '添加拼团商品',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //         {
      //           path: '/combination/edit',
      //           name: 'combinationEdit',
      //           component: () => import('@/views/market/combination/edit.vue'),
      //           meta: {
      //             title: '修改拼团商品',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //       ],
      //     },

      //     {
      //       path: '/market/seckill',
      //       name: 'seckill',
      //       meta: {
      //         title: '秒杀管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: 'ele-Stopwatch',
      //       },
      //       children: [
      //         {
      //           path: '/market/seckillStore',
      //           name: 'seckillStore',
      //           component: () => import('@/views/market/seckill/index.vue'),
      //           meta: {
      //             title: '拼团商品',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-ScaleToOriginal',
      //           },
      //         },
      //         {
      //           path: '/market/seckillList',
      //           name: 'seckillList',
      //           component: () => import('@/views/market/seckill/seckillList.vue'),
      //           meta: {
      //             title: '拼团列表',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-ScaleToOriginal',
      //           },
      //         },
      //         {
      //           path: '/seckill/add',
      //           name: 'seckillAdd',
      //           component: () => import('@/views/market/seckill/add.vue'),
      //           meta: {
      //             title: '添加拼团商品',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //         {
      //           path: '/seckill/edit',
      //           name: 'seckillEdit',
      //           component: () => import('@/views/market/seckill/edit.vue'),
      //           meta: {
      //             title: '修改拼团商品',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //       ],
      //     },
      //     {
      //       path: '/market/carousels',
      //       name: 'carousels',
      //       component: () => import('@/views/market/carousels/index.vue'),
      //       meta: {
      //         title: '轮播图管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-ScaleToOriginal',
      //       },
      //     },
      //     {
      //       path: '/market/draw',
      //       name: 'draw',
      //       component: () => import('@/views/market/draw/index.vue'),
      //       meta: {
      //         title: '抽奖管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-ScaleToOriginal',
      //       },
      //     },
      //     {
      //       path: '/market/depositConfig',
      //       name: 'depositConfigIndex',
      //       component: () => import('@/views/market/depositConfig/index.vue'),
      //       meta: {
      //         page: 'market/depositConfig/index',
      //         title: '充值配置管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director'],
      //         icon: 'ele-ScaleToOriginal',
      //       },
      //     },
      //     {
      //       path: '/market/keyword',
      //       name: 'keywordList',
      //       component: () => import('@/views/market/keyword/index.vue'),
      //       meta: {
      //         title: '搜索关键字管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-Stopwatch',
      //       },
      //     },

      //     {
      //       path: '/market/coupons',
      //       name: 'couponsList',
      //       component: () => import('@/views/market/coupons/index.vue'),
      //       meta: {
      //         title: '优惠券管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-Stopwatch',
      //       },
      //       children: [
      //         {
      //           path: '/market/coupons/list',
      //           name: 'memberCoupons',
      //           component: () => import('@/views/market/coupons/index.vue'),
      //           meta: {
      //             page: 'market/coupons/list',
      //             title: '优惠券列表',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-User',
      //           },
      //         },
      //         {
      //           path: '/market/coupons/edit',
      //           name: 'CouponsEdit',
      //           component: () => import('@/views/market/coupons/edit.vue'),
      //           meta: {
      //             title: '修改优惠卷',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //         {
      //           path: '/market/coupons/add',
      //           name: 'CouponsAdd',
      //           component: () => import('@/views/market/coupons/add.vue'),
      //           meta: {
      //             title: '添加优惠卷',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         }
      //       ],
      //     },
      //     {
      //       path: '/market/card',
      //       name: 'card',
      //       component: () => import('@/views/market/card/index.vue'),
      //       meta: {
      //         title: '卡券管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'cashier'],
      //         icon: 'ele-Stopwatch',
      //       },
      //       children: [
      //         {
      //           path: '/market/card/list',
      //           name: 'cardList',
      //           component: () => import('@/views/market/card/index.vue'),
      //           meta: {
      //             page: 'market/card/list',
      //             title: '卡券列表',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-User',
      //           },
      //         },
      //         {
      //           path: '/market/card/edit',
      //           name: 'cardEdit',
      //           component: () => import('@/views/market/card/edit.vue'),
      //           meta: {
      //             title: '修改卡券',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //         {
      //           path: '/market/card/add',
      //           name: 'cardAdd',
      //           component: () => import('@/views/market/card/add.vue'),
      //           meta: {
      //             title: '添加卡券',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //       ],
      //     },
      //     {
      //       path: '/market/integral',
      //       name: 'integralList',
      //       component: () => import('@/views/integral/order/index.vue'),
      //       meta: {
      //         title: '积分管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: 'ele-Stopwatch',
      //       },
      //       children: [
      //         {
      //           path: '/market/integral/list',
      //           name: 'integralCoupons',
      //           component: () => import('@/views/integral/order/index.vue'),
      //           meta: {
      //             title: '积分订单',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-User',
      //           },
      //         },
      //         {
      //           path: '/integral/commodity/add',
      //           name: 'integralCommodityAdd',
      //           component: () => import('@/views/integral/commodity/add.vue'),
      //           meta: {
      //             title: '添加积分商品',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //         {
      //           path: '/integral/commodity/edit',
      //           name: 'integralCommodityedit',
      //           component: () => import('@/views/integral/commodity/edit.vue'),
      //           meta: {
      //             title: '修改积分商品',
      //             isLink: '',
      //             isHide: true,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: '',
      //           },
      //         },
      //         {
      //           path: '/market/integral/commodity',
      //           name: 'integralCommodity',
      //           component: () => import('@/views/integral/commodity/index.vue'),
      //           meta: {
      //             title: '积分商品',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-User',
      //           },
      //         },
      //         {
      //           path: '/market/integral/configuration',
      //           name: 'integralConfiguration',
      //           component: () =>
      //             import('@/views/integral/configuration/index.vue'),
      //           meta: {
      //             title: '积分配置',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director'],
      //             icon: 'ele-User',
      //           },
      //         },
      //         {
      //           path: '/market/integral/category',
      //           name: 'integralCategory',
      //           component: () => import('@/views/integral/category/index.vue'),
      //           meta: {
      //             title: '积分分类',
      //             isLink: '',
      //             isHide: false,
      //             isKeepAlive: true,
      //             isAffix: false,
      //             isIframe: false,
      //             roles: ['admin', 'director', 'cashier'],
      //             icon: 'ele-User',
      //           },
      //         },
      //       ],
      //     },
      //   ],
      // },
      // {
      //   path: '/distribution',
      //   name: 'distribution',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/distribution/dealerLevel',
      //   meta: {
      //     title: '分销',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin'],
      //     icon: 'ele-MagicStick',
      //   },
      //   children: [
      //     {
      //       path: '/distribution/dealerLevel',
      //       name: 'dealerLevel',
      //       component: () =>
      //         import('@/views/distribution/dealerLevel/index.vue'),
      //       meta: {
      //         title: '分销员等级管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: 'ele-ScaleToOriginal',
      //       },
      //     },
      //   ],
      // },
      // {
      //   path: '/article',
      //   name: 'article',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/article/index',
      //   meta: {
      //     title: '文章',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin'],
      //     icon: 'ele-Document',
      //   },
      //   children: [
      //     {
      //       path: '/article/index',
      //       name: 'articleIndex',
      //       component: () => import('@/views/article/index.vue'),
      //       meta: {
      //         title: '文章列表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: 'ele-Document',
      //       },
      //     },
      //     {
      //       path: '/article/add',
      //       name: 'articleAdd',
      //       component: () => import('@/views/article/add.vue'),
      //       meta: {
      //         page: 'article/add',
      //         title: '添加文章',
      //         isLink: '',
      //         isHide: true,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: '',
      //       },
      //     },
      //     {
      //       path: '/article/edit',
      //       name: 'articleEdit',
      //       component: () => import('@/views/article/edit.vue'),
      //       meta: {
      //         page: 'article/edit',
      //         title: '修改文章',
      //         isLink: '',
      //         isHide: true,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: '',
      //       },
      //     },
      //     {
      //       path: '/article/category',
      //       name: 'articleCategoryIndex',
      //       component: () => import('@/views/article/category/index.vue'),
      //       meta: {
      //         page: 'article/category/index',
      //         title: '分类管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin'],
      //         icon: 'ele-Grid',
      //       },
      //     },
      //   ],
      // },
      // {
      //   path: '/finance',
      //   name: 'finance',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/finance/voucher',
      //   meta: {
      //     title: '财务',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin'],
      //     icon: 'ele-Coin',
      //   },
      //   children: [
      //     {
      //       path: '/finance/voucher',
      //       name: 'voucherIndex',
      //       component: () => import('@/views/finance/voucher/index.vue'),
      //       meta: {
      //         title: '日常收支管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance'],
      //         icon: 'ele-Tickets',
      //       },
      //     },
      //     {
      //       path: '/finance/voucher/category',
      //       name: 'voucherCategory',
      //       component: () => import('@/views/finance/voucher/category/index.vue'),
      //       meta: {
      //         title: '收支类目管理',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance'],
      //         icon: 'ele-Tickets',
      //       },
      //     },
      //   ],
      // },
      // {
      //   path: '/stat',
      //   name: 'stat',
      //   component: () => import('@/layout/routerView/parent.vue'),
      //   redirect: '/stat/orderStat',
      //   meta: {
      //     page: 'layout/routerView/parent',
      //     title: '报表',
      //     isLink: '',
      //     isHide: false,
      //     isKeepAlive: true,
      //     isAffix: false,
      //     isIframe: false,
      //     roles: ['admin', 'director', 'finance'],
      //     icon: 'ele-DataLine',
      //   },
      //   children: [
      //     {
      //       path: '/stat/orderStat',
      //       name: 'orderStat',
      //       component: () => import('@/views/stat/orderStat/index.vue'),
      //       meta: {
      //         page: 'stat/orderStat/index',
      //         title: '商品销售统计',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance'],
      //         icon: 'svg-order',
      //       },
      //     },
      //     // {
      //     //   path: '/stat/staffCommission',
      //     //   name: 'staffCommission',
      //     //   component: () => import('@/views/stat/staffCommission/index.vue'),
      //     //   meta: {
      //     //     page: 'stat/staffCommission/index',
      //     //     title: '员工销售统计',
      //     //     isLink: '',
      //     //     isHide: false,
      //     //     isKeepAlive: true,
      //     //     isAffix: false,
      //     //     isIframe: false,
      //     //     roles: ['admin', 'director', 'finance'],
      //     //     icon: 'svg-order',
      //     //   },
      //     // },
      //     {
      //       path: '/stat/staffCommissionStat',
      //       name: 'staffCommissionStat',
      //       component: () => import('@/views/stat/staffCommissionStat/index.vue'),
      //       meta: {
      //         page: 'stat/staffCommissionStat/index',
      //         title: '日销产品统计表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance'],
      //         icon: 'svg-order',
      //       },
      //     },
      //     // {
      //     //   path: '/stat/staffDepositStat',
      //     //   name: 'staffDepositStat',
      //     //   component: () => import('@/views/stat/staffDepositStat/index.vue'),
      //     //   meta: {
      //     //     page: 'stat/staffDepositStat/index',
      //     //     title: '日会员卡充值统计表',
      //     //     isLink: '',
      //     //     isHide: false,
      //     //     isKeepAlive: true,
      //     //     isAffix: false,
      //     //     isIframe: false,
      //     //     roles: ['admin', 'director', 'finance'],
      //     //     icon: 'svg-order',
      //     //   },
      //     // },
      //     // {
      //     //   path: '/stat/memberStat',
      //     //   name: 'memberStat',
      //     //   component: () => import('@/views/stat/memberStat/index.vue'),
      //     //   meta: {
      //     //     page: 'stat/memberStat/index',
      //     //     title: '会员统计总表',
      //     //     isLink: '',
      //     //     isHide: false,
      //     //     isKeepAlive: true,
      //     //     isAffix: false,
      //     //     isIframe: false,
      //     //     roles: ['admin', 'director', 'finance'],
      //     //     icon: 'svg-order',
      //     //   },
      //     // },
      //     {
      //       path: '/stat/productStat',
      //       name: 'productStat',
      //       component: () => import('@/views/stat/productStat/index.vue'),
      //       meta: {
      //         page: 'stat/productStat/index',
      //         title: '商品销售统计总表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance'],
      //         icon: 'svg-order',
      //       },
      //     },
      //     {
      //       path: '/stat/yearStat',
      //       name: 'yearStat',
      //       component: () => import('@/views/stat/yearStat/index.vue'),
      //       meta: {
      //         page: 'stat/yearStat/index',
      //         title: '年度统计总表',
      //         isLink: '',
      //         isHide: false,
      //         isKeepAlive: true,
      //         isAffix: false,
      //         isIframe: false,
      //         roles: ['admin', 'director', 'finance'],
      //         icon: 'svg-order',
      //       },
      //     },
      //   ],
      // },
      {
        path: '/system',
        name: 'system',
        component: () => import('@/layout/routerView/parent.vue'),
        redirect: '/system/password',
        meta: {
          title: '系统',
          isLink: '',
          isHide: false,
          isKeepAlive: true,
          isAffix: false,
          isIframe: false,
          roles: ['admin', 'director', 'finance', 'cashier', 'warehouse', 'driver', 'vouching'],
          icon: 'iconfont icon-xitongshezhi',
        },
        children: [
          {
            path: '/system/user',
            name: 'systemUser',
            component: () => import('@/views/system/user/index.vue'),
            meta: {
              title: '管理员管理',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'iconfont icon-user',
            },
          },
          {
            path: '/system/payMethod',
            name: 'systemPayMethod',
            component: () => import('@/views/system/payMethod/index.vue'),
            meta: {
              page: 'system/payMethod/index',
              title: '支付方式配置',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'iconfont icon-xitongshezhi',
            },
          },
          {
            path: '/system/config',
            name: 'systemConfigIndex',
            component: () => import('@/views/system/config/index.vue'),
            meta: {
              page: 'system/config/index',
              title: '参数配置',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'iconfont icon-xitongshezhi',
            },
          },
          {
            path: '/system/log',
            name: 'systemLog',
            component: () => import('@/views/system/log/index.vue'),
            meta: {
              title: '操作日志',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'ele-Memo',
            },
          },
          {
            path: '/system/password',
            name: 'systemPassword',
            component: () => import('@/views/system/password/index.vue'),
            meta: {
              title: '修改密码',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin', 'director', 'finance', 'cashier', 'warehouse', 'driver', 'vouching'],
              icon: 'ele-Lock',
            },
          },
          {
            path: '/system/setting',
            name: 'systemSetting',
            component: () => import('@/views/system/setting/index.vue'),
            meta: {
              title: '系统设置',
              isLink: '',
              isHide: false,
              isKeepAlive: true,
              isAffix: false,
              isIframe: false,
              roles: ['admin'],
              icon: 'ele-Lock',
            },
          },
        ],
      },
    ],
  },
]

/**
 * 定义404、401界面
 * /srclink 参考：https://next.router.vuejs.org/zh/guide/essentials/history-mode.html#netlify
 */
export const notFoundAndNoPower = [
  {
    path: '/:path(.*)*',
    name: 'notFound',
    component: () => import('@/views/error/404.vue'),
    meta: {
      title: '找不到此页面',
      isHide: true,
    },
  },
  {
    path: '/401',
    name: 'noPower',
    component: () => import('@/views/error/401.vue'),
    meta: {
      title: '没有权限',
      isHide: true,
    },
  },
]

/**
 * 定义静态路由（默认路由）
 * 此路由不要动，前端添加路由的话，请在 `dynamicRoutes 数组` 中添加
 * /srcdescription 前端控制直接改 dynamicRoutes 中的路由，后端控制不需要修改，请求接口路由数据时，会覆盖 dynamicRoutes 第一个顶级 children 的内容（全屏，不包含 layout 中的路由出口）
 * /srcreturns 返回路由菜单数据
 */
export const staticRoutes: Array<RouteRecordRaw> = [
  {
    path: '/login',
    name: 'login',
    component: () => import('@/views/login/index.vue'),
    meta: {
      title: '登录',
    },
  },
]
